export interface ClassData {
  className: string;
  baseHitPoint: number;
  baseMagicPoint: number;
  baseAttack: number;
  baseDefense: number;
  baseMagic: number;
  baseAgility: number;
  hasAppearanceLvHitPointBonus: boolean;
  hasAppearanceLvMagicPointBonus: boolean;
  hasAppearanceLvAttackBonus: boolean;
  hasAppearanceLvDefenseBonus: boolean;
  hasAppearanceLvMagicBonus: boolean;
  hasAppearanceLvAgilityBonus: boolean;
  growHitPoint: number;
  growMagicPoint: number;
  growAttack: number;
  growDefense: number;
  growMagic: number;
  growAgility: number;
  throwLv0: number | null;
  throwLv1: number | null;
  throwLv2: number | null;
  throwLv3: number | null;
  catchLv0: number | null;
  catchLv1: number | null;
  catchLv2: number | null;
  catchLv3: number | null;
  counterLv0: number | null;
  counterLv1: number | null;
  counterLv2: number | null;
  counterLv3: number | null;
  jumpLv0: number | null;
  jumpLv1: number | null;
  jumpLv2: number | null;
  jumpLv3: number | null;
  exp: number;
  addAbilityName1: string | null;
  addAbilityLv1: number | null;
  addAbilityExp1: number | null;
  addAbilityType1: number | null;
  addAbilityRequireLv1: number | null;
  addAbilityName2: string | null;
  addAbilityLv2: number | null;
  addAbilityExp2: number | null;
  addAbilityType2: number | null;
  addAbilityRequireLv2: number | null;
  addAbilityName3: string | null;
  addAbilityLv3: number | null;
  addAbilityExp3: number | null;
  addAbilityType3: number | null;
  addAbilityRequireLv3: number | null;
  addAbilityName4: string | null;
  addAbilityLv4: number | null;
  addAbilityExp4: number | null;
  addAbilityType4: number | null;
  addAbilityRequireLv4: number | null;
  addAbilityName5: string | null;
  addAbilityLv5: number | null;
  addAbilityExp5: number | null;
  addAbilityType5: number | null;
  addAbilityRequireLv5: number | null;
  addAbilityName6: string | null;
  addAbilityLv6: number | null;
  addAbilityExp6: number | null;
  addAbilityType6: number | null;
  addAbilityRequireLv6: number | null;
}
