/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * An explanation about the purpose of this instance.
 */
export type TheNameSchema = string;
/**
 * An explanation about the purpose of this instance.
 */
export type TheClassnameSchema = string;
/**
 * An explanation about the purpose of this instance.
 */
export type TheElementSchema = string;
/**
 * An explanation about the purpose of this instance.
 */
export type TheWeapontype1Schema = string | null;
/**
 * An explanation about the purpose of this instance.
 */
export type TheWeaponskilllv1Schema = number | null;
/**
 * An explanation about the purpose of this instance.
 */
export type TheWeapontype2Schema = string | null;
/**
 * An explanation about the purpose of this instance.
 */
export type TheWeaponskilllv2Schema = number | null;
/**
 * An explanation about the purpose of this instance.
 */
export type TheWeapontype3Schema = string | null;
/**
 * An explanation about the purpose of this instance.
 */
export type TheWeaponskilllv3Schema = number | null;
/**
 * An explanation about the purpose of this instance.
 */
export type TheDefaultequipment1Schema = string | null;
/**
 * An explanation about the purpose of this instance.
 */
export type TheDefaultequipmentattack1Schema = number | null;
/**
 * An explanation about the purpose of this instance.
 */
export type TheDefaultequipment2Schema = string | null;
/**
 * An explanation about the purpose of this instance.
 */
export type TheDefaultequipmentattack2Schema = number | null;
/**
 * An explanation about the purpose of this instance.
 */
export type TheDefaultequipment3Schema = string | null;
/**
 * An explanation about the purpose of this instance.
 */
export type TheDefaultequipmentattack3Schema = number | null;
/**
 * An explanation about the purpose of this instance.
 */
export type TheBasicattackmodifierSchema = number;
/**
 * An explanation about the purpose of this instance.
 */
export type TheBasicdefensemodifierSchema = number;
/**
 * An explanation about the purpose of this instance.
 */
export type TheBasicmagicmodifierSchema = number;
/**
 * An explanation about the purpose of this instance.
 */
export type TheBasicagilitymodifierSchema = number;
/**
 * An explanation about the purpose of this instance.
 */
export type TheBasicmoveSchema = number;
/**
 * An explanation about the purpose of this instance.
 */
export type TheBasicmagicdefenseSchema = number;
/**
 * An explanation about the purpose of this instance.
 */
export type TheBasicdodgeSchema = number;
/**
 * An explanation about the purpose of this instance.
 */
export type TheBasicguardSchema = number;
/**
 * An explanation about the purpose of this instance.
 */
export type TheConditiontypeSchema = string;
/**
 * An explanation about the purpose of this instance.
 */
export type TheRavishrateSchema = string;
/**
 * An explanation about the purpose of this instance.
 */
export type TheStealableitemSchema = string | null;
/**
 * An explanation about the purpose of this instance.
 */
export type TheDroppableitemSchema = string | null;
/**
 * An explanation about the purpose of this instance.
 */
export type TheClasschangelvSchema = number | null;
/**
 * An explanation about the purpose of this instance.
 */
export type TheClasschangespSchema = number | null;
/**
 * An explanation about the purpose of this instance.
 */
export type TheIshumanSchema = boolean;
/**
 * An explanation about the purpose of this instance.
 */
export type TheIsmaleSchema = boolean;
/**
 * An explanation about the purpose of this instance.
 */
export type TheIsfemaleSchema = boolean;
/**
 * An explanation about the purpose of this instance.
 */
export type TheIsflyableSchema = boolean;
/**
 * An explanation about the purpose of this instance.
 */
export type TheIsundeadSchema = boolean;
/**
 * An explanation about the purpose of this instance.
 */
export type TheSlayerSchema = string;
/**
 * An explanation about the purpose of this instance.
 */
export type TheFrontdamegescaleSchema = number;
/**
 * An explanation about the purpose of this instance.
 */
export type TheSidedamegescaleSchema = number;
/**
 * An explanation about the purpose of this instance.
 */
export type TheBackdamegescaleSchema = number;
/**
 * An explanation about the purpose of this instance.
 */
export type TheEquipmenteffecttypeSchema = string | null;
/**
 * An explanation about the purpose of this instance.
 */
export type TheBooknumberSchema = number;
/**
 * An explanation about the purpose of this instance.
 */
export type TheInternalnumberSchema = string;
/**
 * An explanation about the purpose of this instance.
 */
export type TheBooklvSchema = number | null;
/**
 * An explanation about the purpose of this instance.
 */
export type TheProfileSchema = string;
/**
 * An explanation about the purpose of this instance.
 */
export type TheMaxlvSchema = number;
/**
 * An explanation about the purpose of this instance.
 */
export type TheIsequipablearmorSchema = boolean;
/**
 * An explanation about the purpose of this instance.
 */
export type TheAbilityname1Schema = string | null;
/**
 * An explanation about the purpose of this instance.
 */
export type TheDefaultabilitylv1Schema = number | null;
/**
 * An explanation about the purpose of this instance.
 */
export type TheAbilityexp1Schema = number | null;
/**
 * An explanation about the purpose of this instance.
 */
export type TheAbilitygrowthtype1Schema = number | null;
/**
 * An explanation about the purpose of this instance.
 */
export type TheAbilityname2Schema = string | null;
/**
 * An explanation about the purpose of this instance.
 */
export type TheDefaultabilitylv2Schema = number | null;
/**
 * An explanation about the purpose of this instance.
 */
export type TheAbilityexp2Schema = number | null;
/**
 * An explanation about the purpose of this instance.
 */
export type TheAbilitygrowthtype2Schema = number | null;
/**
 * An explanation about the purpose of this instance.
 */
export type TheAbilityname3Schema = string | null;
/**
 * An explanation about the purpose of this instance.
 */
export type TheDefaultabilitylv3Schema = number | null;
/**
 * An explanation about the purpose of this instance.
 */
export type TheAbilityexp3Schema = number | null;
/**
 * An explanation about the purpose of this instance.
 */
export type TheAbilitygrowthtype3Schema = number | null;
/**
 * An explanation about the purpose of this instance.
 */
export type TheAbilityname4Schema = string | null;
/**
 * An explanation about the purpose of this instance.
 */
export type TheDefaultabilitylv4Schema = number | null;
/**
 * An explanation about the purpose of this instance.
 */
export type TheAbilityexp4Schema = number | null;
/**
 * An explanation about the purpose of this instance.
 */
export type TheAbilitygrowthtype4Schema = number | null;
/**
 * An explanation about the purpose of this instance.
 */
export type TheAbilityname5Schema = string | null;
/**
 * An explanation about the purpose of this instance.
 */
export type TheDefaultabilitylv5Schema = number | null;
/**
 * An explanation about the purpose of this instance.
 */
export type TheAbilityexp5Schema = number | null;
/**
 * An explanation about the purpose of this instance.
 */
export type TheAbilitygrowthtype5Schema = number | null;
/**
 * An explanation about the purpose of this instance.
 */
export type TheAbilityname6Schema = string | null;
/**
 * An explanation about the purpose of this instance.
 */
export type TheDefaultabilitylv6Schema = number | null;
/**
 * An explanation about the purpose of this instance.
 */
export type TheAbilityexp6Schema = number | null;
/**
 * An explanation about the purpose of this instance.
 */
export type TheAbilitygrowthtype6Schema = number | null;
/**
 * An explanation about the purpose of this instance.
 */
export type TheAbilityname7Schema = string | null;
/**
 * An explanation about the purpose of this instance.
 */
export type TheDefaultabilitylv7Schema = number | null;
/**
 * An explanation about the purpose of this instance.
 */
export type TheAbilityexp7Schema = number | null;
/**
 * An explanation about the purpose of this instance.
 */
export type TheAbilitygrowthtype7Schema = number | null;
/**
 * An explanation about the purpose of this instance.
 */
export type TheAbilityname8Schema = string | null;
/**
 * An explanation about the purpose of this instance.
 */
export type TheDefaultabilitylv8Schema = number | null;
/**
 * An explanation about the purpose of this instance.
 */
export type TheAbilityexp8Schema = number | null;
/**
 * An explanation about the purpose of this instance.
 */
export type TheAbilitygrowthtype8Schema = number | null;
/**
 * An explanation about the purpose of this instance.
 */
export type TheAbilityposition1Schema = number | null;
/**
 * An explanation about the purpose of this instance.
 */
export type TheAbilityposition2Schema = number | null;
/**
 * An explanation about the purpose of this instance.
 */
export type TheAbilityposition3Schema = number | null;
/**
 * An explanation about the purpose of this instance.
 */
export type TheAbilityposition4Schema = number | null;
/**
 * An explanation about the purpose of this instance.
 */
export type TheAbilityposition5Schema = number | null;
/**
 * An explanation about the purpose of this instance.
 */
export type TheAbilityposition6Schema = number | null;
/**
 * An explanation about the purpose of this instance.
 */
export type TheAbilityposition7Schema = number | null;
/**
 * An explanation about the purpose of this instance.
 */
export type TheAbilityposition8Schema = number | null;

/**
 * The root schema comprises the entire JSON document.
 */
export interface UnitData {
  name: TheNameSchema;
  className: TheClassnameSchema;
  element: TheElementSchema;
  weaponType1: TheWeapontype1Schema;
  weaponSkillLv1: TheWeaponskilllv1Schema;
  weaponType2: TheWeapontype2Schema;
  weaponSkillLv2: TheWeaponskilllv2Schema;
  weaponType3: TheWeapontype3Schema;
  weaponSkillLv3: TheWeaponskilllv3Schema;
  defaultEquipment1: TheDefaultequipment1Schema;
  defaultEquipmentAttack1: TheDefaultequipmentattack1Schema;
  defaultEquipment2: TheDefaultequipment2Schema;
  defaultEquipmentAttack2: TheDefaultequipmentattack2Schema;
  defaultEquipment3: TheDefaultequipment3Schema;
  defaultEquipmentAttack3: TheDefaultequipmentattack3Schema;
  basicAttackModifier: TheBasicattackmodifierSchema;
  basicDefenseModifier: TheBasicdefensemodifierSchema;
  basicMagicModifier: TheBasicmagicmodifierSchema;
  basicAgilityModifier: TheBasicagilitymodifierSchema;
  basicMove: TheBasicmoveSchema;
  basicMagicDefense: TheBasicmagicdefenseSchema;
  basicDodge: TheBasicdodgeSchema;
  basicGuard: TheBasicguardSchema;
  conditionType: TheConditiontypeSchema;
  ravishRate: TheRavishrateSchema;
  stealableItem: TheStealableitemSchema;
  droppableItem: TheDroppableitemSchema;
  classChangeLv: TheClasschangelvSchema;
  classChangeSp: TheClasschangespSchema;
  isHuman: TheIshumanSchema;
  isMale: TheIsmaleSchema;
  isFemale: TheIsfemaleSchema;
  isFlyable: TheIsflyableSchema;
  isUndead: TheIsundeadSchema;
  slayer: TheSlayerSchema;
  frontDamegeScale: TheFrontdamegescaleSchema;
  sideDamegeScale: TheSidedamegescaleSchema;
  backDamegeScale: TheBackdamegescaleSchema;
  equipmentEffectType: TheEquipmenteffecttypeSchema;
  bookNumber: TheBooknumberSchema;
  internalNumber: TheInternalnumberSchema;
  bookLv: TheBooklvSchema;
  profile: TheProfileSchema;
  maxLv: TheMaxlvSchema;
  isEquipableArmor: TheIsequipablearmorSchema;
  abilityName1: TheAbilityname1Schema;
  defaultAbilityLv1: TheDefaultabilitylv1Schema;
  abilityExp1: TheAbilityexp1Schema;
  abilityGrowthType1: TheAbilitygrowthtype1Schema;
  abilityName2: TheAbilityname2Schema;
  defaultAbilityLv2: TheDefaultabilitylv2Schema;
  abilityExp2: TheAbilityexp2Schema;
  abilityGrowthType2: TheAbilitygrowthtype2Schema;
  abilityName3: TheAbilityname3Schema;
  defaultAbilityLv3: TheDefaultabilitylv3Schema;
  abilityExp3: TheAbilityexp3Schema;
  abilityGrowthType3: TheAbilitygrowthtype3Schema;
  abilityName4: TheAbilityname4Schema;
  defaultAbilityLv4: TheDefaultabilitylv4Schema;
  abilityExp4: TheAbilityexp4Schema;
  abilityGrowthType4: TheAbilitygrowthtype4Schema;
  abilityName5: TheAbilityname5Schema;
  defaultAbilityLv5: TheDefaultabilitylv5Schema;
  abilityExp5: TheAbilityexp5Schema;
  abilityGrowthType5: TheAbilitygrowthtype5Schema;
  abilityName6: TheAbilityname6Schema;
  defaultAbilityLv6: TheDefaultabilitylv6Schema;
  abilityExp6: TheAbilityexp6Schema;
  abilityGrowthType6: TheAbilitygrowthtype6Schema;
  abilityName7: TheAbilityname7Schema;
  defaultAbilityLv7: TheDefaultabilitylv7Schema;
  abilityExp7: TheAbilityexp7Schema;
  abilityGrowthType7: TheAbilitygrowthtype7Schema;
  abilityName8: TheAbilityname8Schema;
  defaultAbilityLv8: TheDefaultabilitylv8Schema;
  abilityExp8: TheAbilityexp8Schema;
  abilityGrowthType8: TheAbilitygrowthtype8Schema;
  abilityPosition1: TheAbilityposition1Schema;
  abilityPosition2: TheAbilityposition2Schema;
  abilityPosition3: TheAbilityposition3Schema;
  abilityPosition4: TheAbilityposition4Schema;
  abilityPosition5: TheAbilityposition5Schema;
  abilityPosition6: TheAbilityposition6Schema;
  abilityPosition7: TheAbilityposition7Schema;
  abilityPosition8: TheAbilityposition8Schema;
  [k: string]: any;
}
